'use client';

import { useEffect, useMemo, useState } from 'react';

type Project = { id: number; title: string; category: string; stack: string[]; status: string; score: number };
const seed: Project[] = [
  { id: 1, title: 'AI Content Studio', category: 'AI', stack: ['Next.js', 'OpenAI', 'Supabase'], status: 'Live', score: 98 },
  { id: 2, title: 'Crypto Dashboard', category: 'Data', stack: ['JavaScript', 'REST API', 'CSS'], status: 'Live', score: 94 },
  { id: 3, title: 'Weather Pro', category: 'API', stack: ['HTML', 'CSS', 'JavaScript'], status: 'Live', score: 91 },
  { id: 4, title: 'Snake Game', category: 'Games', stack: ['JavaScript', 'Canvas', 'CSS'], status: 'Completed', score: 88 },
  { id: 5, title: 'SocialHub', category: 'Full Stack', stack: ['React', 'Node.js', 'SQL'], status: 'Beta', score: 96 },
  { id: 6, title: 'Portfolio CMS', category: 'Full Stack', stack: ['Next.js', 'PostgreSQL', 'Tailwind'], status: 'Building', score: 93 },
];

export default function Home() {
  const [projects, setProjects] = useState<Project[]>(seed);
  const [filter, setFilter] = useState('All'); const [query, setQuery] = useState(''); const [dark, setDark] = useState(false);
  const [showForm, setShowForm] = useState(false); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [message, setMessage] = useState(''); const [notice, setNotice] = useState('');
  const [newTitle, setNewTitle] = useState(''); const [newCategory, setNewCategory] = useState('Full Stack'); const [newStack, setNewStack] = useState('HTML, CSS, JavaScript');

  useEffect(() => { const saved = localStorage.getItem('devforge-projects'); if (saved) setProjects(JSON.parse(saved)); const theme = localStorage.getItem('devforge-theme'); if (theme === 'dark') setDark(true); }, []);
  useEffect(() => { localStorage.setItem('devforge-projects', JSON.stringify(projects)); }, [projects]);
  useEffect(() => { localStorage.setItem('devforge-theme', dark ? 'dark' : 'light'); }, [dark]);

  const categories = ['All', ...Array.from(new Set(projects.map(p => p.category)))];
  const visible = useMemo(() => projects.filter(p => (filter === 'All' || p.category === filter) && `${p.title} ${p.stack.join(' ')}`.toLowerCase().includes(query.toLowerCase())), [projects, filter, query]);
  const addProject = (e: React.FormEvent) => { e.preventDefault(); if (!newTitle.trim()) return; setProjects([...projects, { id: Date.now(), title: newTitle.trim(), category: newCategory, stack: newStack.split(',').map(x => x.trim()).filter(Boolean), status: 'New', score: 100 }]); setNewTitle(''); setNewStack('HTML, CSS, JavaScript'); setShowForm(false); setNotice('Proyecto agregado correctamente.'); };
  const removeProject = (id: number) => { setProjects(projects.filter(p => p.id !== id)); setNotice('Proyecto eliminado.'); };
  const sendContact = (e: React.FormEvent) => { e.preventDefault(); if (!name || !email || !message) return setNotice('Completa todos los campos.'); setNotice(`Gracias ${name}. Tu mensaje fue validado correctamente.`); setName(''); setEmail(''); setMessage(''); };

  return <main className={dark ? 'min-h-screen bg-slate-950 text-white' : 'min-h-screen bg-slate-50 text-slate-950'}>
    <nav className="sticky top-0 z-50 border-b border-slate-200/20 bg-white/90 px-5 py-4 backdrop-blur dark:bg-slate-950/90"><div className="mx-auto flex max-w-7xl items-center justify-between"><a href="#home" className="text-xl font-black"><span className="text-cyan-500">&lt;/&gt;</span> DevForge</a><div className="hidden gap-6 text-sm font-bold md:flex"><a href="#home">Home</a><a href="#projects">Projects</a><a href="#stack">Stack</a><a href="#contact">Contact</a></div><button onClick={() => setDark(!dark)} className="rounded-full border px-4 py-2 text-xs font-bold">{dark ? '☀ Light' : '◐ Dark'}</button></div></nav>

    <section id="home" className="mx-auto grid max-w-7xl gap-10 px-5 py-20 lg:grid-cols-[1.2fr_.8fr] lg:items-center"><div><span className="rounded-full bg-cyan-400/10 px-4 py-2 text-xs font-bold uppercase tracking-widest text-cyan-500">Functional full-stack demo</span><h1 className="mt-6 text-5xl font-black sm:text-7xl">Code ideas.<br/><span className="text-cyan-500">Ship products.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 opacity-70">Una aplicación funcional con JavaScript, React, Next.js, SQL, APIs, almacenamiento local y arquitectura preparada para Supabase.</p><div className="mt-8 flex gap-3"><a href="#projects" className="rounded-xl bg-cyan-500 px-6 py-3 font-bold text-slate-950">Probar aplicación →</a><a href="#contact" className="rounded-xl border px-6 py-3 font-bold">Contactar</a></div></div><div className="rounded-[2rem] bg-slate-950 p-6 text-white shadow-2xl"><div className="flex justify-between"><b>System status</b><span className="text-emerald-400">● Online</span></div><div className="mt-8 grid grid-cols-2 gap-3">{[[projects.length,'Projects'],['8','Technologies'],['100%','Interactive'],['0','Dead buttons']].map(([v,l]) => <div key={String(l)} className="rounded-2xl border border-white/10 p-5"><b className="text-2xl">{v}</b><div className="text-xs text-slate-400">{l}</div></div>)}</div></div></section>

    <section id="projects" className="border-y border-slate-200/20 py-16"><div className="mx-auto max-w-7xl px-5"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-bold uppercase tracking-widest text-cyan-500">CRUD + JavaScript</p><h2 className="text-4xl font-black">Project database</h2></div><div className="flex gap-2"><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Buscar..." className="rounded-xl border bg-transparent px-4 py-3"/><button onClick={() => setShowForm(!showForm)} className="rounded-xl bg-cyan-500 px-4 py-3 font-bold text-slate-950">+ Nuevo</button></div></div>
      {showForm && <form onSubmit={addProject} className="mt-6 grid gap-3 rounded-2xl border p-5 md:grid-cols-4"><input required value={newTitle} onChange={e => setNewTitle(e.target.value)} placeholder="Nombre" className="rounded-xl border bg-transparent p-3"/><select value={newCategory} onChange={e => setNewCategory(e.target.value)} className="rounded-xl border bg-transparent p-3"><option>Full Stack</option><option>AI</option><option>Data</option><option>API</option><option>Games</option></select><input value={newStack} onChange={e => setNewStack(e.target.value)} placeholder="Tecnologías separadas por coma" className="rounded-xl border bg-transparent p-3"/><button className="rounded-xl bg-cyan-500 font-bold text-slate-950">Guardar</button></form>}
      <div className="mt-6 flex flex-wrap gap-2">{categories.map(c => <button key={c} onClick={() => setFilter(c)} className={filter === c ? 'rounded-full bg-cyan-500 px-4 py-2 font-bold text-slate-950' : 'rounded-full border px-4 py-2 font-semibold'}>{c}</button>)}</div>
      <div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{visible.map(p => <article key={p.id} className="rounded-3xl border p-6 transition hover:-translate-y-1 hover:border-cyan-400"><div className="flex justify-between"><span className="text-xs font-bold text-cyan-500">{p.category}</span><b>{p.score}%</b></div><h3 className="mt-5 text-xl font-black">{p.title}</h3><div className="mt-5 flex flex-wrap gap-2">{p.stack.map(t => <span key={t} className="rounded-md border px-2 py-1 text-xs">{t}</span>)}</div><div className="mt-6 flex justify-between border-t pt-4 text-sm"><span>{p.status}</span><button onClick={() => removeProject(p.id)} className="font-bold text-red-400">Eliminar</button></div></article>)}</div>{!visible.length && <p className="py-12 text-center opacity-60">No hay resultados.</p>}</div></section>

    <section id="stack" className="mx-auto max-w-7xl px-5 py-16"><p className="text-sm font-bold uppercase tracking-widest text-cyan-500">Technology</p><h2 className="mt-2 text-4xl font-black">Stack utilizado</h2><div className="mt-8 grid grid-cols-2 gap-4 sm:grid-cols-4 lg:grid-cols-8">{['HTML5','CSS3','JavaScript','TypeScript','React','Next.js','Node.js','SQL'].map(t => <div key={t} className="rounded-2xl border p-5 text-center font-bold">{t}</div>)}</div></section>

    <section id="contact" className="mx-5 mb-12 rounded-[2rem] bg-slate-950 px-6 py-12 text-white sm:px-12"><div className="mx-auto max-w-3xl"><p className="text-sm font-bold uppercase tracking-widest text-cyan-400">Form validation</p><h2 className="mt-3 text-4xl font-black">Contact</h2><form onSubmit={sendContact} className="mt-8 grid gap-4"><input required value={name} onChange={e => setName(e.target.value)} placeholder="Nombre" className="rounded-xl border border-white/10 bg-white/5 p-4"/><input required type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="Email" className="rounded-xl border border-white/10 bg-white/5 p-4"/><textarea required value={message} onChange={e => setMessage(e.target.value)} placeholder="Mensaje" rows={5} className="rounded-xl border border-white/10 bg-white/5 p-4"/><button className="rounded-xl bg-cyan-500 px-6 py-3 font-bold text-slate-950">Enviar mensaje</button></form>{notice && <p className="mt-4 rounded-xl bg-cyan-500/10 p-4 text-cyan-300">{notice}</p>}</div></section>
    <footer className="border-t px-5 py-8 text-center text-sm opacity-50">DevForge · Full-stack functional project · Next.js + React + TypeScript + SQL</footer>
  </main>;
}
